### ISSUE TITLE
submitted task lists no longer show up

### ISSUE THREAD

**Issue by shkfnly** [distribute-protocol/distribute-app#42]
**Describe the bug**
On the Add Tasks page the submissions of the tasks no longer show up.

**Expected behavior**
Tasks should be added to the submissions page.

**Comment by shkfnly** [comment]
This now works, however the prelim task list is added through both a mutation in an epic and a log on the server, this probably should not be the case given the possibility of race conditions

**Comment by jessicagmarshall** [comment]
I updated the epic to create the prelim task list first, then call the contract. the log double checks the contact of, and updates this prelim task list with the remaining information, namely the weighting and the verification. this is no longer a race condition.
